# Save notification message
SAVE_MSG="run-shell '#{@resurrect-save-script-path} quiet'"

# Window structure changes
# set-hook -g after-split-window $SAVE_MSG
# # set-hook -g after-kill-pane $SAVE_MSG
# set-hook -g window-linked $SAVE_MSG
# # set-hook -g window-unlinked $SAVE_MSG
# set-hook -g window-renamed $SAVE_MSG
# # set-hook -g window-resized $SAVE_MSG
#
# # Session changes
# set-hook -g session-created $SAVE_MSG
# set-hook -g session-renamed $SAVE_MSG
# set-hook -g session-closed $SAVE_MSG

# Pane events
# set-hook -g pane-exited $SAVE_MSG

