
[mgr]
prepend_keymap = [
	{ on = "l", run = "plugin smart-enter", desc = "enter the child directory, or open the file" },
	{ on = "i", run = "spot", desc = "file information spotter" },
	{ on = "m", run = "plugin mount" },
	{ on = "f", run = "plugin smart-filter", desc = "smart filter" },
	{ on = "<c-j>", run = "arrow 1", desc = "smart filter" },
	{ on = ["c", "m"], run = "plugin chmod", desc = "chmod on selected files" },
	{ on = ["c", "p"], run = '''shell 'printf "%s" "$0" | pbcopy' --confirm''', desc = "copy current path to clipboard" },
	{ on = [";", "w"], run = "cd ~/code/work/", desc = "work directory" },
	{ on = [";", "s"], run = "cd ~/code/scolaire/", desc = "school directory" },
	{ on = [";", "c"], run = "cd ~/.config/", desc = "config directory" },
	{ on = [";", "h"], run = "cd ~/", desc = "home directory" },
	{ on = [";", "d"], run = "cd ~/downloads", desc = "downloads" },
	{ on = [";", "p"], run = "cd ~/code/projects/", desc = "code projects" },
	{ on = [";", "t"], run = "cd .trash/", desc = "trash folder" },
	{ on = "y", run = ['''shell 'fish -c "copy_file \"$@\""' ''', "yank"] },
	{ on = [";", "u"], run = "cd /volumes", desc = "mounted volumes" },
	{ on = [";", "d"], run = "cd '/users/grimaldev/library/mobile documents/com~apple~clouddocs/documents'", desc = "icloud documents" },
	{ on = "s", run = '''shell 'fish -c "share \"$@\""' --confirm''', desc = "share file" },
	{ on = "o", run = ['''shell 'fish -c "open \"$@\""' ''', "quit"], desc = "open file and quit yazi" },
	{ on = "z", run = '''shell 'fish -c "zathura \"$@\" & disown"' ''', desc = "open pdf with zathura" },
	{ on = "<c-o>", run = "plugin fzf", desc = "fuzzy search in current folder" },
	{ on = "e", run = "7zz x '$f' -o'$d'", desc = "extract archive with 7zz" },
	{ on = "<c-s>", run = 'shell --block --confirm "sesh connect "$0" && exit"', desc = "quit and connect to sesh session" },
	{ on = "<c-p>", run = ["sort mtime --reverse", "arrow top"], desc = "Go to newest folder" },
	{ on = "<c-n>", run = ["sort mtime --reverse=no", "arrow bot"], desc = "Jump to newest file" },
]

# prepend_keymap = [
# 	{ on = "q", run = '''shell "kitty @ close-window --self" no_wait''', desc = "Quit yazi" },
# ]

# prepend_keymap = [
# 	{ on = "q", run = '''shell 'osascript -e "tell application \"System Events\" to keystroke \"q\" using {command down}"' ''', desc = "Quit yazi" },
# ]

