
[mgr]
prepend_keymap = [
	{ on = "l", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
	{ on = "i", run = "spot", desc = "File information spotter" },
	{ on = "M", run = "plugin mount" },
	{ on = "F", run = "plugin smart-filter", desc = "Smart filter" },
	{ on = "<C-j>", run = "arrow 1", desc = "Smart filter" },
	{ on = ["c", "m"], run = "plugin chmod", desc = "Chmod on selected files" },
	{ on = [";", "w"], run = "cd ~/Code/Work/", desc = "Work directory" },
	{ on = [";", "s"], run = "cd ~/Code/Scolaire/", desc = "School directory" },
	{ on = [";", "c"], run = "cd ~/.config/", desc = "Config directory" },
	{ on = [";", "h"], run = "cd ~/", desc = "Home directory" },
	{ on = [";", "d"], run = "cd ~/Downloads", desc = "Downloads" },
	{ on = [";", "p"], run = "cd ~/Code/Projects/", desc = "Code projects" },
	{ on = [";", "t"], run = "cd .Trash/", desc = "Trash folder" },
	{ on = "y", run = ['''shell 'fish -c "copy_file \"$@\""' ''', "yank"] },
	{ on = [";", "u"], run = "cd /Volumes", desc = "Mounted volumes" },
	{ on = [";", "D"], run = "cd '/Users/grimaldev/Library/Mobile Documents/com~apple~CloudDocs/documents'", desc = "Icloud Documents" },
	{ on = "S", run = '''shell 'fish -c "share \"$@\""' --confirm''', desc = "Share file" },
	{ on = "o", run = ['''shell 'fish -c "open \"$@\""' ''', "quit"], desc = "Open file and quit yazi" },
	{ on = "z", run = '''shell 'fish -c "zathura \"$@\" & disown"' ''', desc = "Open PDF with Zathura" },
	{ on = "s", run = "plugin fzf", desc = "Fuzzy search in current folder" },
	{ on = "e", run = "7zz x '$f' -o'$d'", desc = "Extract archive with 7zz" },
	{ on = "<C-s>", run = 'shell --block --confirm "sesh connect "$0" && exit"', desc = "Quit and connect to sesh session" },
]

# prepend_keymap = [
# 	{ on = "q", run = '''shell "kitty @ close-window --self" no_wait''', desc = "Quit yazi" },
# ]

# prepend_keymap = [
# 	{ on = "q", run = '''shell 'osascript -e "tell application \"System Events\" to keystroke \"q\" using {command down}"' ''', desc = "Quit yazi" },
# ]

