# Autostart Configuration
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Authentification
exec-once = systemctl --user start hyprpolkitagent

# Background apps at launch
exec-once = wl-paste --watch cliphist store
# exec-once = systemctl --user start xremap
exec-once = 1password
exec-once = hyprpaper
exec-once = mako
exec-once = foot --server

# Workspace apps
exec-once = [workspace 2 silent] notion-app --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto
exec-once = [workspace 3 silent] zen --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto
exec-once = [workspace 4 silent] kitty -e sesh connect "Home "
exec-once = [workspace 5 silent] kitty -e btop
exec-once = [workspace 9 silent] equibop --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto
