preload = /home/grimaldev/wallpapers/the-last-of-us-part.jpg

wallpaper {
  monitor = DVI-I-1
  path = /home/grimaldev/wallpapers/the-last-of-us-part.jpg
  fit_mode = cover
}

wallpaper {
  monitor = eDP-1
  path = /home/grimaldev/wallpapers/the-last-of-us-part.jpg
  fit_mode = cover
}

splash = false
ipc = on
