# Window Rules Configuration
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

windowrule = opacity $windowOpacity override, match:fullscreen false

windowrule = opaque true, match:class foot|equibop|org\.quickshell|imv|swappy  # They use native transparency or we want them opaque
windowrule = center true, match:float true, match:xwayland false  # Center all floating windows (not xwayland cause popups)

# Workspace rules - workspace 10 on external, rest on internal
workspace = 10, monitor:DVI-I-1

# Workspace assignments
windowrulev2 = workspace 2 silent, match:class Notion
windowrulev2 = workspace 3 silent, match:class firefox|zen
windowrulev2 = workspace 9 silent, match:class equibop

# show me the key floating window
windowrulev2 = float,title:^(Floating Window - Show Me The Key)$
windowrulev2 = noinitialfocus,title:^(Floating Window - Show Me The Key)$
windowrulev2 = noborder,title:^(Floating Window - Show Me The Key)$
windowrulev2 = move 1033 842,title:^(Floating Window - Show Me The Key)$
windowrulev2 = size 491 50,title:^(Floating Window - Show Me The Key)$
windowrulev2 = center, class:(floatingTerm)
windowrulev2 = pin,title:^(Floating Window - Show Me The Key)$

# Opacity rules
windowrulev2 = opacity 1 1,class:^(kitty)$
# windowrulev2 = animation popin,class:^(kitty)$,title:^(update-sys)$
# windowrulev2 = opacity 0.8 0.8,class:^(kitty)$,title:^(ranger)$
windowrulev2 = animation popin,class:^(chromium)$
windowrulev2 = move cursor -3% -105%,class:^(rofi)$
windowrulev2 = noanim,class:^(rofi)$
windowrulev2 = opacity 0.8 0.6,class:^(rofi)$
# windowrulev2 = opacity 0.8 0.8, fullscreen:1

# Dialogs
windowrule = float true, match:title (Select|Open)( a)? (File|Folder)(s)?
windowrule = float true, match:title File (Operation|Upload)( Progress)?
windowrule = float true, match:title .* Properties
windowrule = float true, match:title Export Image as PNG
windowrule = float true, match:title GIMP Crash Debug
windowrule = float true, match:title Save As
windowrule = float true, match:title Library

# Steam
windowrule = rounding 10, match:class steam
windowrule = float true, match:title Friends List, match:class steam
windowrule = immediate true, match:class steam_app_[0-9]+  # Allow tearing for steam games
windowrule = idle_inhibit always, match:class steam_app_[0-9]+  # Always idle inhibit when playing a steam game

# Autodesk Fusion 360
windowrule = no_blur true, match:title Fusion360|(Marking Menu), match:class fusion360\.exe

# Float, resize and center
windowrule = float true, match:class footclient, match:title foot
windowrule = size 1000 700, match:class footclient, match:title foot
windowrule = center 1, match:class footclient, match:title foot
windowrule = float true, match:title Qalculate!
windowrule = size 1000 700, match:title Qalculate!
windowrule = center 1, match:title Qalculate!
windowrule = float true, match:class org\.gnome\.Settings
windowrule = size 70% 80%, match:class org\.gnome\.Settings
windowrule = center 1, match:class org\.gnome\.Settings
windowrule = float true, match:class org\.pulseaudio\.pavucontrol|yad-icon-browser
windowrule = size 60% 70%, match:class org\.pulseaudio\.pavucontrol|yad-icon-browser
windowrule = center 1, match:class org\.pulseaudio\.pavucontrol|yad-icon-browser
windowrule = float true, match:class nwg-look
windowrule = size 50% 60%, match:class nwg-look
windowrule = center 1, match:class nwg-look
