[[session]]
name = "Autodesk ⚙️"
path = "~/.config/Autodesk"


[[session]]
name = 'asciinema ⚙️'
path = '/Users/grimaldev/.config/asciinema'


[[session]]
name = 'bat ⚙️'
path = '/Users/grimaldev/.config/bat'


[[session]]
name = 'btop ⚙️'
path = '/Users/grimaldev/.config/btop'


[[session]]
name = 'filezilla ⚙️'
path = '/Users/grimaldev/.config/filezilla'


[[session]]
name = 'fish ⚙️'
path = '/Users/grimaldev/.config/fish'


[[session]]
name = 'flutter ⚙️'
path = '/Users/grimaldev/.config/flutter'


[[session]]
name = 'gh ⚙️'
path = '/Users/grimaldev/.config/gh'


[[session]]
name = 'github-copilot ⚙️'
path = '/Users/grimaldev/.config/github-copilot'


[[session]]
name = 'karabiner ⚙️'
path = '/Users/grimaldev/.config/karabiner'


[[session]]
name = 'kitty ⚙️'
path = '/Users/grimaldev/.config/kitty'


[[session]]
name = 'lazygit ⚙️'
path = '/Users/grimaldev/.config/lazygit'


[[session]]
name = 'neofetch ⚙️'
path = '/Users/grimaldev/.config/neofetch'


[[session]]
name = 'neovide ⚙️'
path = '/Users/grimaldev/.config/neovide'


[[session]]
name = 'neovim ⚙️'
path = '/Users/grimaldev/.config/neovim'


[[session]]
name = 'nnn ⚙️'
path = '/Users/grimaldev/.config/nnn'


[[session]]
name = 'nvim ⚙️'
path = '/Users/grimaldev/.config/nvim'


[[session]]
name = 'omf ⚙️'
path = '/Users/grimaldev/.config/omf'


[[session]]
name = 'op ⚙️'
path = '/Users/grimaldev/.config/op'


[[session]]
name = 'ranger ⚙️'
path = '/Users/grimaldev/.config/ranger'


[[session]]
name = 'raycast ⚙️'
path = '/Users/grimaldev/.config/raycast'


[[session]]
name = 'rofi ⚙️'
path = '/Users/grimaldev/.config/rofi'


[[session]]
name = 'rofi.root ⚙️'
path = '/Users/grimaldev/.config/rofi.root'


[[session]]
name = 'scripts ⚙️'
path = '/Users/grimaldev/.config/scripts'


[[session]]
name = 'sesh ⚙️'
path = '/Users/grimaldev/.config/sesh'


[[session]]
name = 'sketchybar ⚙️'
path = '/Users/grimaldev/.config/sketchybar'


[[session]]
name = 'skhd ⚙️'
path = '/Users/grimaldev/.config/skhd'


[[session]]
name = 'tmux ⚙️'
path = '/Users/grimaldev/.config/tmux'


[[session]]
name = 'wireshark ⚙️'
path = '/Users/grimaldev/.config/wireshark'


[[session]]
name = 'yabai ⚙️'
path = '/Users/grimaldev/.config/yabai'


