import = [
	"~/.config/sesh/sesh-autogen.toml",
]

[default_session]
startup_command = "nvim"

[[session]]
name = "Home 💻"
path = "~"
startup_command = "clear"

[[session]]
name = "Immozia 🏡"
path = "~/Documents/work/oxianet.nosync/immozia/"
startup_command = "bash $DOTFILES/sesh/scripts/immozia"

[[session]]
name = "SRVWEBSTR01 🌐"
path = "~/Documents/servers/srvwebstr01/"
startup_command = "ssh srvwebstr01 -t 'clear && exec $SHELL'"

[[session]]
name = "PI 🌐"
path = "~/Documents/servers/pi/"
startup_command = "ssh pi -t 'clear && exec $SHELL'"

[[session]]
name = "Nvim ⚙️"
path = "~/.config/nvim/lua"

