[default_session]
startup_command = "nvim"

[[session]]
name = "Home 💻"
path = "~"
startup_command = "ff"

[[session]]
name = "Immozia 🏡"
path = "~/Code/work/oxianet/immozia/"
startup_command = "bash $DOTFILES/sesh/scripts/immozia"

[[session]]
name = "SRVWEBSTR01 🌐"
path = "~/Code/servers/srvwebstr01/"
startup_command = "ssh srvwebstr01 -t 'clear && exec $SHELL'"

[[session]]
name = "PI 🌐"
path = "~/Code/servers/pi/"
startup_command = "ssh pi -t 'clear && exec $SHELL'"

[[session]]
name = "Nvim ⚙️"
path = "~/.config/nvim/lua"

[[session]]
name = "Discord  "
path = "~/.config/discodo"
startup_command = "discordo -t $DISCORD_TOKEN"

[[session]]
name = "Whatsapp  "
path = "~/.config/nchat"
startup_command = "nchat"

import = ["~/.config/sesh/sesh-autogen.toml"]
