#!/usr/bin/env bash
tmux_session="Immozia\ 🏡"

# tmux new-window -c '#{pane_current_path}' -t "${tmux_session}:1" "nvim"
tmux send-keys -t "${tmux_session}:1" "nvim" enter
tmux new-window -c '#{pane_current_path}' -t "${tmux_session}:2"
tmux new-window -c '#{pane_current_path}' -t "${tmux_session}:3" "ssh -L 3346:localhost:3306 -t immozia 'cd /home/immo/www; exec fish -l'"
