#!/usr/bin/env bash
tmux_session="Monitor\ Control\ 🎛️"

tmux send-keys -t "${tmux_session}:1" "nvim" enter
tmux new-window -c '#{pane_current_path}' -t "${tmux_session}:2"
tmux new-window -c '#{pane_current_path}' -t "${tmux_session}:3" "ssh -t baptiste@10.242.20.101 'cd /home/monitor; exec fish -l'"
tmux new-window -c '#{pane_current_path}' -t "${tmux_session}:4"
tmux send-keys -t "${tmux_session}:4" "nvim" enter
tmux send-keys -t "${tmux_session}:4" ":DBUIToggle" enter
